workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Create export options
        script: |
          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>V2N3335468</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>uploadSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF

      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --export-options-plist export_options.plist \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa